// <auto-generated />
#nullable enable
using Microsoft.CodeAnalysis;

namespace EntitiesDb.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class ForEachGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var matches = context.SyntaxProvider
			.CreateSyntaxProvider(Discovery.IsCandidateNode, Discovery.Transform)
			.Where(static cap => cap.IsValid);

		var captures = matches.Collect();

		context.RegisterSourceOutput(captures, static (spc, all) =>
		{
			var seen = new HashSet<string>();
			for (int i = 0; i < all.Length; i++)
			{
				var capture = all[i];
				if (!seen.Add(capture.UniqueName))
					continue;

				var model = ModelBuilder.Build(capture);
				if (model == null || !model.IsValid)
					continue;

				var text = Renderer.Render(model);
				spc.AddSource(model.HintName + ".g.cs", text);
			}
		});
	}
}
